FROM oven/bun:1

WORKDIR /app

# Install OpenSSL for Prisma
RUN apt-get update -y && apt-get install -y openssl

COPY package.json bun.lock turbo.json ./
COPY packages/ ./packages/
COPY apps/web ./apps/web

RUN bun install

RUN bun db:generate

RUN bun run build

EXPOSE 3000

WORKDIR /app/apps/web

CMD ["bun", "run", "start"]
