name: backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Generate Prisma Client
        run: bun db:generate

      - name: Installing deps
        run: bun install

      - name: Build
        run: bun run build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/turbo-frontend:latest

      - name: Build and push Backend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/turbo-backend:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p ~/turbo-app
            cd ~/turbo-app

            cat > compose.yaml << 'EOF'
            services:
              frontend:
                image: ${{ secrets.DOCKER_USERNAME }}/turbo-frontend:latest
                ports:
                  - "3000:3000"
                environment:
                  - DATABASE_URL=postgresql://postgres:2004@db:5432/db
                depends_on:
                  - backend
                  - db

              backend:
                image: ${{ secrets.DOCKER_USERNAME }}/turbo-backend:latest
                ports:
                  - "3001:3001"
                environment:
                  - DATABASE_URL=postgresql://postgres:2004@db:5432/db
                depends_on:
                  - db

              db:
                image: postgres:latest
                container_name: database
                environment:
                  - POSTGRES_USER=postgres
                  - POSTGRES_DB=db
                  - POSTGRES_PASSWORD=2004
                ports:
                  - "5432:5432"
                volumes:
                  - postgres_data:/var/lib/postgresql/data

            volumes:
              postgres_data:
            EOF

            docker pull ${{ secrets.DOCKER_USERNAME }}/turbo-frontend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/turbo-backend:latest
            docker-compose up -d --remove-orphans
