name: backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Generate Prisma Client
        run: bun db:generate

      - name: Installing deps
        run: bun install

      - name: Build
        run: bun run build

  Deploy:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: SSH to ec2
          uses: appleboy/ssh-action@v0.1.6
          with:
            host: ${{ secrets.CIVO_HOST }}
            username: ${{ secrets.CIVO_USER }}
            key: ${{ secrets.CIVO_SSH_KEY }}
            script: |
              cd /home/${{ secrets.CIVO_USER }}/your-project-dir
              git pull origin main
              docker-compose pull
              docker-compose up --build -d --remove-orphans
